name: Gerar Voxali.exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Baixar codigo
      uses: actions/checkout@v4

    - name: Criar pasta do aplicativo
      shell: powershell
      run: |
        mkdir dist
        if (Test-Path "main.js") { Copy-Item "main.js" -Destination "dist" }
        if (Test-Path "package.json") { Copy-Item "package.json" -Destination "dist" }
        if (Test-Path "config.json") { Copy-Item "config.json" -Destination "dist" }
        if (Test-Path "LEIA-ME.md") { Copy-Item "LEIA-ME.md" -Destination "dist" }

    - name: Disponibilizar arquivos para download
      uses: actions/upload-artifact@v4
      with:
        name: Voxali-arquivos-desktop
        path: dist/*
